# Generated by Django 5.2.11 on 2026-02-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name_ar', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('name_ur', models.CharField(blank=True, max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('ayah_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
                'indexes': [models.Index(fields=['number'], name='quran_quran_number_94f28d_idx'), models.Index(fields=['slug'], name='quran_quran_slug_79276b_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuranAyah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_surah', models.PositiveSmallIntegerField()),
                ('text_ar', models.TextField()),
                ('translation_ur', models.TextField(blank=True)),
                ('translation_en', models.TextField(blank=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.quransurah')),
            ],
            options={
                'ordering': ['surah__number', 'number_in_surah'],
                'indexes': [models.Index(fields=['surah', 'number_in_surah'], name='quran_quran_surah_i_ab6f3e_idx')],
                'unique_together': {('surah', 'number_in_surah')},
            },
        ),
    ]
